/**************************************************************************
 * C S 429 architecture emulator
 * 
 * instr.c - The top-level entry point for instruction processing.
 * 
 * Most of the details will be written in files in the instr/ subdirectory.
 * 
 * Copyright (c) 2022. S. Chatterjee. All rights reserved.
 * May not be used, modified, or copied without permission.
 **************************************************************************/ 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "machine.h"
#include "pipe/select_pc.h"
#include "hw_elts.h"

extern machine_t guest;

// The four global variables below are signals that correspond to long wires.
extern uint64_t pred_pc; // Defined in proc.c.
extern uint64_t current_PC; // Defined in proc.c.
static bool X_condval; // Generated in X. Consumed in F.
static uint64_t W_wval; // Generated in W. Consumed in D.

inline unsigned safe_GETBF(int32_t src, unsigned frompos, unsigned width) {
    return ((((unsigned) src) & (((1 << width) - 1) << frompos)) >> frompos);
}

int64_t safe_GETBOFFSET(int32_t src, unsigned frompos, unsigned width) {
    return (
        (int64_t) (((((uint64_t) src) & (((1 << width) - 1) << frompos)) >> frompos) << (64-width))
        >> (64-width)
    );
}

static inline void init_itable_entry(opcode_t op, unsigned idx) {itable[idx] = op;}

static inline void init_itable_range(opcode_t op, unsigned idx1, unsigned idx2) {
    for (unsigned i = idx1; i <= idx2; i++) itable[i] = op;
}

/*
 * Initialize the itable. Called from interface.c.
 * Do not re-write.
 */

void init_itable(void) {
    for (int i = 0; i < (2<<11); i++) itable[i] = OP_ERROR;
    init_itable_entry(OP_LDURB, 0x1c2U);
    init_itable_entry(OP_LDUR, 0x7c2U);
    init_itable_entry(OP_STURB, 0x1c0U);
    init_itable_entry(OP_STUR, 0x7c0U);
    init_itable_range(OP_MOVK, 0x794U, 0x797U);
    init_itable_range(OP_MOVZ, 0x694U, 0x697U);
    init_itable_range(OP_ADD_RI, 0x488U, 0x48bU);
    init_itable_entry(OP_ADDS_RR, 0x558U);
    init_itable_entry(OP_SUBS_RR, 0x758U);
    init_itable_entry(OP_MVN, 0x551U);
    init_itable_entry(OP_ORR_RR, 0x550U);
    init_itable_entry(OP_EOR_RR, 0x650U);
    init_itable_entry(OP_ANDS_RR, 0x750U);
    init_itable_range(OP_UBFM, 0x69aU, 0x69bU); // LSL, LSR share the same opcode
    init_itable_range(OP_ASR, 0x49aU, 0x49bU);
    init_itable_range(OP_B, 0x0a0U, 0x0bfU);
    init_itable_range(OP_B_COND, 0x2a0U, 0x2a7U);
    init_itable_range(OP_BL, 0x4a0U, 0x4bfU);
    init_itable_entry(OP_RET, 0x6b2U);
    init_itable_entry(OP_NOP, 0x6a8U);
    init_itable_entry(OP_HLT, 0x6a2U);
}

/*
 * Select PC logic.
 * STUDENT TO-DO:
 * Write the next PC to current_PC.
 */

static comb_logic_t 
select_PC(uint64_t pred_PC, opcode_t X_opcode, bool X_cond_val, uint64_t seq_succ, opcode_t D_opcode, uint64_t val_a,
          uint64_t *current_PC) {
    return;
}

/*
 * Predict PC logic. Conditional branches are predicted taken.
 * STUDENT TO-DO:
 * Write the predicted next PC to predicted_PC
 * and the next sequential pc to seq_succ.
 */

static comb_logic_t 
predict_PC(uint64_t current_PC, uint32_t insnbits, opcode_t op, uint64_t *predicted_PC, uint64_t *seq_succ) {
    return;
}

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally. 
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t 
generate_DXMW_control(opcode_t op,
                      d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs) {
    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to imm.
 */

static comb_logic_t 
extract_immval(uint32_t insnbits, int64_t *imm) {
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

static comb_logic_t 
copy_m_ctl_sigs(pipe_reg_t *const insn) {
    return;
}

static comb_logic_t 
copy_w_ctl_sigs(pipe_reg_t *const insn) {
    return;
}

/*
 * Fetch stage logic.
 * STUDENT TO-DO:
 * Implement the fetch stage.
 * 
 * You will also need the global variables
 * current_PC, pred_pc, X_condval, and itable,
 * and helper functions
 * select_pc, predict_pc, and imem.
 */

comb_logic_t fetch_instr(pipe_reg_t *const insn) {
    bool imem_err; // Ignored, though you will need this as a filler parameter to imem.
    return;
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 * 
 * You will need the global variable W_wval
 * and helper functions
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(pipe_reg_t *const insn) {
    return;
}

/*
 * Execute stage logic.
 * STUDENT TO-DO:
 * Implement the execute stage.
 * 
 * You will need the helper functions
 * copy_m_ctl_signals, copy_w_ctl_signals, and alu.
 */

comb_logic_t execute_instr(pipe_reg_t *const insn) {
    return;
}

/*
 * Memory stage logic.
 * STUDENT TO-DO:
 * Implement the memory stage.
 * 
 * You will need the helper functions
 * copy_m_ctl_signals, copy_w_ctl_signals, and dmem.
 */

comb_logic_t memory_instr(pipe_reg_t *const insn) {
    bool dmem_err; // Ignored, though you will need this as a filler parameter to dmem.
    return;
}

/*
 * Write-back stage logic.
 * STUDENT TO-DO:
 * Implement the writeback stage.
 * 
 * You will need the global variable W_wval
 * and the helper function copy_w_ctl_sigs.
 */

comb_logic_t wback_instr(pipe_reg_t *const insn) {
    return;
}

static char *opcode_names[] = {
    "ERR ", 
    "LDURB ",
    "LDUR ",
    "STURB ",
    "STUR ",
    "MOVK ",
    "MOVZ ",
    "ADD ",
    "ADDS ",
    "SUBS ",
    "MVN ",
    "ORR ",
    "EOR ",
    "ANDS ",
    "LSL ",
    "LSR ",
    "UBFM ",
    "ASR ",
    "B ",
    "B.cond ",
    "BL ",
    "RET ",
    "NOP ",
    "HLT ",
};

static char *cond_names[] = {
    "EQ", "NE", "CS", "CC", "MI", "PL", "VS", "VC", 
    "HI", "LS", "GE", "LT", "GT", "LE", "AL", "NV"
};

static char *alu_op_names[] = {
    "PLUS_OP",
    "MINUS_OP",
    "NEG_OP",
    "OR_OP",
    "EOR_OP",
    "AND_OP",
    "MOV_OP",
    "LSL_OP",
    "LSR_OP",
    "ASR_OP",
    "PASS_A_OP",
    "PASS_B_OP"
};


/*
 * A debugging aid to print out the fields of an instruction.
 * This routine is called from runElf().
 * Do not re-write.
 * 
 * The amount of detail printed is controlled by debug_level.
 *  0: No output.
 *  1: Medium output. Data signals only in the pipeline register.
 *  2: Full output. Data and control signals in the pipeline register.
 */

void show_instr(const instr_impl_t *insn, const proc_stage_t stage, int debug_level) {
    
    if(debug_level < 1) {
        return;
    }

    switch (stage) {
    case S_FETCH:
        printf("F: %-6s[PC, insn_bits] = [%08lX,  %08X], seq_succ_PC: 0x%lX, pred_PC: 0x%lX\n", 
            opcode_names[insn->op],
            guest.proc->PC.bits->xval, 
            insn->insnbits,
            insn->seq_succ_PC,
            pred_pc);

        if (debug_level == 1)
            break;
        
        // debug level 2: also print control signals
        printf(" \t [bubble, stall] = [%s, %s]\n",
            insn->bubble ? "true" : "false",
            insn->stall ? "true" : "false");
        break;
    case S_DECODE:
        printf("D: %-6s[val_a, val_b, imm] = [0x%lX, 0x%lX, 0x%lX], alu_op: %s, cond: %s, dst: X%d\n",
            opcode_names[insn->op],
            insn->val_a,
            insn->val_b,
            insn->val_imm,
            alu_op_names[insn->ALU_op],
            cond_names[insn->cond],
            insn->dst);
        if (debug_level == 1)
            break;
        
        // debug level 2: also print control signals
        printf(" \t [bubble, stall] = [%s, %s]\n",
            insn->bubble ? "true" : "false",
            insn->stall ? "true" : "false");

        printf("\t X_sigs: [valb_sel, set_CC] = [%s, %s]\n",
            insn->X_sigs.valb_sel ? "true " : "false",
            insn->X_sigs.set_CC ? "true" : "false");

        printf("\t M_sigs: [dmem_read, dmem_write] = [%s, %s]\n",
            insn->M_sigs.dmem_read ? "true " : "false",
            insn->M_sigs.dmem_write ? "true" : "false");

        printf("\t W_sigs: [dst_31isSP, dst_sel, wval_sel, w_enable] = [%s, %s, %s, %s]\n",
            insn->W_sigs.dst_31isSP ? "true " : "false",
            insn->W_sigs.dst_sel ? "true " : "false",
            insn->W_sigs.wval_sel ? "true " : "false",
            insn->W_sigs.w_enable ? "true" : "false");

        break;

        case S_EXECUTE: 
            printf("X: %-6s[val_ex, a, b, imm, hw] = [0x%lX, 0x%lX, 0x%lX, 0x%lX, 0x%X], alu_op: %s\n",
                opcode_names[insn->op],
                insn->val_ex,
                insn->val_a,
                insn->val_b,
                insn->val_imm,
                insn->val_hw,
                alu_op_names[insn->ALU_op]);
            if (debug_level == 1)
                break;
        
            // debug level 2: also print control signals
            printf(" \t [bubble, stall] = [%s, %s]\n",
                insn->bubble ? "true" : "false",
                insn->stall ? "true" : "false");

            printf("\t X_sigs: [valb_sel, set_CC] = [%s, %s]\n",
            insn->X_sigs.valb_sel ? "true " : "false",
            insn->X_sigs.set_CC ? "true" : "false");

            break;
        case S_MEMORY: 
            printf("M: %-6s[val_ex, val_b, val_mem] = [0x%lX, 0x%lX, 0x%lX]\n",
                opcode_names[insn->op],
                insn->val_ex,
                insn->val_b,
                insn->val_mem);

            if (debug_level == 1)
                break;
        
            // debug level 2: also print control signals
            printf(" \t [bubble, stall] = [%s, %s]\n",
                insn->bubble ? "true" : "false",
                insn->stall ? "true" : "false");

            printf("\t M_sigs: [dmem_read, dmem_write] = [%s, %s]\n",
                insn->M_sigs.dmem_read ? "true " : "false",
                insn->M_sigs.dmem_write ? "true" : "false");

            break;
        case S_WBACK: 
            printf("W: %-6s[dst, val_ex, val_mem] = [X%d, 0x%lX, 0x%lX]\n",
                opcode_names[insn->op],
                insn->dst,
                insn->val_ex,
                insn->val_mem);

            if (debug_level == 1)
                break;
        
            // debug level 2: also print control signals
            printf(" \t [bubble, stall] = [%s, %s]\n",
                insn->bubble ? "true" : "false",
                insn->stall ? "true" : "false");
            
            printf("\t W_sigs: [dst_31isSP, dst_sel, wval_sel, w_enable] = [%s, %s, %s, %s]\n",
                insn->W_sigs.dst_31isSP ? "true " : "false",
                insn->W_sigs.dst_sel ? "true " : "false",
                insn->W_sigs.wval_sel ? "true " : "false",
                insn->W_sigs.w_enable ? "true" : "false");

            break;
        default: IMPOSSIBLE(); break;
    }
    return;
}
